import PDFDocument from "pdfkit";

export interface BirthCertificateData {
  referenceNumber: string;
  childFullName: string;
  dateOfBirth: string;
  placeOfBirth: string;
  sex: string;
  motherFullName: string;
  fatherFullName?: string;
  issuedAt: string;
}

/** Renders a simple, legible certificate. Streams PDF bytes into a Buffer. */
export function renderBirthCertificatePdf(data: BirthCertificateData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 60 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(10).fillColor("#555").text("REPUBLIC OF MALAWI", { align: "center" });
    doc.moveDown(0.2);
    doc.fontSize(18).fillColor("#000").text("Malawi OneGov — Civil Registration", { align: "center" });
    doc.fontSize(22).text("Certificate of Birth", { align: "center" });
    doc.moveDown(1.5);

    doc.rect(50, doc.y, doc.page.width - 100, 1).fill("#cccccc");
    doc.moveDown(1);

    const row = (label: string, value: string) => {
      doc.fontSize(11).fillColor("#555").text(label, { continued: true });
      doc.fillColor("#000").text(`  ${value}`);
      doc.moveDown(0.6);
    };

    row("Reference Number:", data.referenceNumber);
    row("Full Name of Child:", data.childFullName);
    row("Date of Birth:", data.dateOfBirth);
    row("Place of Birth:", data.placeOfBirth);
    row("Sex:", data.sex);
    row("Mother's Full Name:", data.motherFullName);
    if (data.fatherFullName) row("Father's Full Name:", data.fatherFullName);
    row("Date Issued:", data.issuedAt);

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#777").text(
      "This is a digitally issued certificate generated by the Malawi OneGov platform. " +
        "Its authenticity can be verified against the immutable audit trail using the reference number above.",
      { align: "left" }
    );

    doc.end();
  });
}

export interface TradingLicenseData {
  referenceNumber: string;
  businessName: string;
  businessType: string;
  tradingAddress: string;
  district: string;
  ownerFullName: string;
  issuedAt: string;
}

/** Renders a Trading Licence certificate. Streams PDF bytes into a Buffer. */
export function renderTradingLicenseCertificatePdf(data: TradingLicenseData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 60 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(10).fillColor("#555").text("REPUBLIC OF MALAWI", { align: "center" });
    doc.moveDown(0.2);
    doc.fontSize(18).fillColor("#000").text("Malawi OneGov — Business Licensing", { align: "center" });
    doc.fontSize(22).text("Trading Licence", { align: "center" });
    doc.moveDown(1.5);

    doc.rect(50, doc.y, doc.page.width - 100, 1).fill("#cccccc");
    doc.moveDown(1);

    const row = (label: string, value: string) => {
      doc.fontSize(11).fillColor("#555").text(label, { continued: true });
      doc.fillColor("#000").text(`  ${value}`);
      doc.moveDown(0.6);
    };

    row("Reference Number:", data.referenceNumber);
    row("Business Name:", data.businessName);
    row("Business Type:", data.businessType);
    row("Trading Address:", data.tradingAddress);
    row("District:", data.district);
    row("Owner:", data.ownerFullName);
    row("Date Issued:", data.issuedAt);

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#777").text(
      "This is a digitally issued licence generated by the Malawi OneGov platform. " +
        "Its authenticity can be verified against the immutable audit trail using the reference number above.",
      { align: "left" }
    );

    doc.end();
  });
}
